### ISSUE TITLE
Getting full citation span

### ISSUE THREAD

**Issue by overmode** [freelawproject/eyecite#135]
Hi, thank you for the great library !

## Problem description
I am preparing a dataset, in which I would like to _mask_ some citations, e.g. replacing them by "[CITATION]".
I could not find a way to get the _full_ span of the citation. Indeed, only the normalized part is covered by the builtin span() function (see below)  

 ```
 import eyecite         
        
citations = [
    'Commonwealth v. Gibson, 561 A.2d 1240 1242',
    'Commonwealth v. Bauer, 604 A.2d 1098 (Pa.Super. 1992)'
]

for citation in citations :
    print('\n', '='*20)
    extracted_citation = eyecite.get_citations(citation)[0]
    print(extracted_citation)
    
    start_idx = extracted_citation.span()[0]
    end_idx = extracted_citation.span()[1]
    
    before_cit = citation[:start_idx]
    cit_text = citation[start_idx:end_idx]
    after_cit = citation[end_idx:]
    print(f"{before_cit} [BEGIN] {cit_text} [END] {after_cit}")
```

output :

```
====================
FullCaseCitation('561 A.2d 1240', groups={'volume': '561', 'reporter': 'A.2d', 'page': '1240'}, metadata=FullCaseCitation.Metadata(parenthetical=None, pin_cite='1242', year=None, court=None, plaintiff='Commonwealth', defendant='Gibson', extra=None))
Commonwealth v. Gibson,  [BEGIN] 561 A.2d 1240 [END]  1242

 ====================
FullCaseCitation('604 A.2d 1098', groups={'volume': '604', 'reporter': 'A.2d', 'page': '1098'}, metadata=FullCaseCitation.Metadata(parenthetical=None, pin_cite=None, year='1992', court=None, plaintiff='Commonwealth', defendant='Bauer', extra=None))
Commonwealth v. Bauer,  [BEGIN] 604 A.2d 1098 [END]  (Pa.Super. 1992)
```
One can see that the span only partially covers the citation text.
If possible, I would like to avoid using regex for recovering the _full_ span.
Concatenating the lengths of the citation's attributes (plaintiff, defendant, etc.) does not seem to be a viable solution as well, because the second example misses the "Pa. Super" text.

## Desired behavior
It would be nice to have a 'full_span()' function such that, if I use it instead of span() in the above example, I get 
```
====================
FullCaseCitation('561 A.2d 1240', groups={'volume': '561', 'reporter': 'A.2d', 'page': '1240'}, metadata=FullCaseCitation.Metadata(parenthetical=None, pin_cite='1242', year=None, court=None, plaintiff='Commonwealth', defendant='Gibson', extra=None))
 [BEGIN]Commonwealth v. Gibson, 561 A.2d 1240 1242[END]

 ====================
FullCaseCitation('604 A.2d 1098', groups={'volume': '604', 'reporter': 'A.2d', 'page': '1098'}, metadata=FullCaseCitation.Metadata(parenthetical=None, pin_cite=None, year='1992', court=None, plaintiff='Commonwealth', defendant='Bauer', extra=None))
[BEGIN]Commonwealth v. Bauer,  604 A.2d 1098 (Pa.Super. 1992)[END] 
```

## Specs
eyecite version : 2.4.0

**Comment by mlissner** [comment]
Is the idea, @overmode, to remove all citations to make it better training data?

**Comment by overmode** [comment]
Hey, thanks for the quick reply.
@mlissner  Indeed, the idea is to build a training set for some machine learning application.

I took note of your method, it's ok if the recall of citation extraction is not excellent because I have many documents anyway, but I will need a way to tell whether the parsing went well to at least have a good precision.

@flooie I tried the eyecite.models.FullCaseCitation.corrected_citation_full method, it does break at the second example :

```
====================
EXTRACTED : FullCaseCitation('561 A.2d 1240', groups={'volume': '561', 'reporter': 'A.2d', 'page': '1240'}, metadata=FullCaseCitation.Metadata(parenthetical=None, pin_cite='1242', year=None, court=None, plaintiff='Commonwealth', defendant='Gibson', extra=None))
CORRECTED_CITATION_FULL : Commonwealth v. Gibson, 561 A.2d 1240, 1242
CITATION SPAN : Commonwealth v. Gibson,  [BEGIN] 561 A.2d 1240 [END]  1242

 ====================
EXTRACTED : FullCaseCitation('604 A.2d 1098', groups={'volume': '604', 'reporter': 'A.2d', 'page': '1098'}, metadata=FullCaseCitation.Metadata(parenthetical=None, pin_cite=None, year='1992', court=None, plaintiff='Commonwealth', defendant='Bauer', extra=None))
Error executing job with overrides: []
Traceback (most recent call last):
  File "check_samples.py", line 59, in main
    print('CORRECTED_CITATION_FULL :', extracted_citation.corrected_citation_full())
  File "/home/ubuntu/.local/lib/python3.8/site-packages/eyecite/models.py", line 361, in corrected_citation_full
    publisher_date = " ".join(m[i] for i in (m.court, m.year) if i)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/eyecite/models.py", line 361, in <genexpr>
    publisher_date = " ".join(m[i] for i in (m.court, m.year) if i)
TypeError: 'Metadata' object is not subscriptable
```

This is not exactly what I would0 like, though, because it is not exact text that was matched.
Is there a better way to find back the latter text ?

Also, Is this the bug you pointed out ? I'm open to a PR in case there is no better workaround, so I would appreciate if you have insights to share already.

**Comment by mattdahl** [comment]
Just chiming in here since I saw your PR (#136) and was surprised that this wasn't already possible! Thanks for implementing it!

Separate from your changes in the PR, I was also curious about the court issue. It seems that the `Pa.Super.` is not being extracted properly because the `citation_string` listed for the PA Superior Court is `"Pa. Super. Ct."` (line 46902 here: https://github.com/freelawproject/courts-db/blob/main/courts_db/data/courts.json). The problem is the space between the `Pa.` and the `Super.`. This also seems like something that should be fixed -- would it cause problems to just ignore whitespace when matching court abbreviations here: https://github.com/freelawproject/eyecite/blob/main/eyecite/helpers.py#L52? May be related to the changes proposed in #129

**Comment by overmode** [comment]
@mattdahl Thanks ! 
Maybe we should consider moving away from exact string matching and use simple regex instead ? 
For instance in `r'\s*pa\s+super\s*'`, we would not be dependent on the spacing, and we could also make it robust to punctuation.
I don't think it would hurt speed a lot

**Comment by flooie** [comment]
@overmode every time I see the words `simple` and `regex` I get nervous.  I'm not sure I see how this relatively simple situation is resolved with regex.

**Comment by overmode** [comment]
I understand, regexes are powerful but scale badly.
Well, the equivalent in python here would be to remove all punctuation and spaces, and then look for 'pasuper'.
I think the question was more whether it would not work in some corner cases, and you are much more knowledgeable than I am.

**Comment by mlissner** [comment]
For the court issue, the question is essentially, "What bad things will happen if we broaden how we match court strings against the text?" 

Honestly, I don't think anybody knows. Right now we do two things. We:

 - Strip the punctuation with `string_puc`, and we
 - Use `startswith` to strip terminal periods, which sometimes seem to interfere

If we went a step further and matched with regexes or by taking out whitespace, would we have false matches? I don't know, but I know how to check! 

If we want to run this down, I think the trick is to look at the `citation_string` values for every court in the courts DB and see what happens if you strip out spaces in addition to stripping out punctuation. I think it might be fine, but what we'd want to watch out for are two courts with nearly identical citation strings that overlap due to this. If there's no collisions caused by that analysis, I'd say yeah, let's add a third step to how we normalize and compare citation strings.

**Comment by mattdahl** [comment]
Here's a gist doing that collision test: https://gist.github.com/mattdahl/a563a48ac512275d893907dd19acd4ae

It doesn't seem that removing whitespace causes any additional collisions, so I think we can safely do that. However, the fact that there are so many existing collisions also suggests that we probably shouldn't just be uncritically accepting the first match, as currently implemented.

**Comment by mlissner** [comment]
> However, the fact that there are so many existing collisions also suggests that we probably shouldn't just be uncritically accepting the first match, as currently implemented.

Yeah, that jumped out at me too. @flooie what's your take on that?

**Comment by flooie** [comment]
> Here's a gist doing that collision test: https://gist.github.com/mattdahl/a563a48ac512275d893907dd19acd4ae
> 
> It doesn't seem that removing whitespace causes any additional collisions, so I think we can safely do that. However, the fact that there are so many existing collisions also suggests that we probably shouldn't just be uncritically accepting the first match, as currently implemented.
<img width="796" alt="Screenshot 2023-01-25 at 2 42 41 PM" src="https://user-images.githubusercontent.com/6464529/214671420-5ed56253-be9d-4f09-92b9-ac73221e3e19.png">

**Comment by flooie** [comment]
@mattdahl - we had imported a lot of courts - that were low level county, town courts and in ny a few of courts had been generated with the parent citation string.

For example, New York County Court -> has like 50+ County courts and they were generated with N.Y. Cty. Ct. as the citation string instead of NY Cty. Ct., Suffolk Cty. ... etc.   I went thru and fixed the 100 or so collisions

**Comment by mattdahl** [comment]
Nice!! The only duplicate left is `N.Y. Cty. Ct., Nassau Cty.` -- is that intentional?

**Comment by flooie** [comment]
no- ha - thats just a duplicate court.  I'll strip that in a second.  I have a few things to add about courts and citation strings.  Ill add momentarily

**Comment by flooie** [comment]
@quevon24 can we investigate this - this may ... should be done?  but lets do this as research if its not

**Comment by quevon24** [comment]
These are my observations @flooie 

1.- This PR fixes the issue to detect court correctly: https://github.com/freelawproject/eyecite/pull/144
2.- I'm not entirely sure that it's necessary to add anything new to eyecite, if the goal is to have the original text with the BEGIN and END embeddings we could do something like this using the full span on the original text.

```
citations = [
    'Commonwealth v. Gibson, 561 A.2d 1240 1242',
    'Commonwealth v. Bauer, 604 A.2d 1098 (Pa. Super. 1992)',
]
for citation in citations:
    print('\n', '=' * 20)
    find_citations = get_citations(citation)
    if find_citations:
        extracted_citation = find_citations[0]
        print(f"[BEGIN]{citation[extracted_citation.full_span()[0]:extracted_citation.full_span()[1]]}[END]")
```

This should work because the span and full_span values are from the original string, not from the text we get from corrected_citation_full() method.

**Comment by mattdahl** [comment]
Circling back to this, the (sub)issue regarding the normalization in `corrected_citation_full()` remains. For example:

```
get_citations('PWS Holding Corp., 228 F.3d 224 (3rd Cir. 2000)')[0].corrected_citation_full()
```
Returns: '228 F.3d 224 (**ca3** 2000)'

Am I correct that we all agree this is not desirable? If so, is there a problem with just doing a reverse lookup in https://github.com/freelawproject/courts-db/blob/main/courts_db/data/courts.json to insert the normalized `citation_string` instead of the `id`?
